# Generated by Django 4.2.2 on 2023-07-04 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0002_userprofile_email_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="catgrory",
            new_name="category",
        ),
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 7, 4, 10, 18, 46, 874879, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
