# Generated by Django 4.2.2 on 2023-07-05 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0004_remove_item_category_item_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(
            model_name="item",
            name="user",
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Fashion", "Fashion"),
                    ("Home and Garden", "Home and Garden"),
                    ("Sports and Outdoors", "Sports and Outdoors"),
                    ("Beauty and Health", "Beauty and Health"),
                    ("Toys and Games", "Toys and Games"),
                ],
                default="Uncategorized",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="interested_items", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
